#!/usr/bin/env node
// Converts a Postgres pg_dump (--column-inserts, public schema) into a D1-compatible SQL file.
// Usage: node scripts/convert-pg-dump.mjs <input.sql> <output.sql>

import { readFileSync, writeFileSync } from 'node:fs';

const [, , inPath, outPath] = process.argv;
if (!inPath || !outPath) {
  console.error('Usage: node scripts/convert-pg-dump.mjs <input.sql> <output.sql>');
  process.exit(1);
}

// Parent-first ordering so foreign keys resolve without needing PRAGMA tweaks.
const TABLES = ['goals', 'exercises', 'goal_exercises', 'goal_logs', 'exercise_logs'];
const KEEP_RE = new RegExp(`^INSERT INTO public\\.(${TABLES.join('|')}) `);

const src = readFileSync(inPath, 'utf8');

const byTable = Object.fromEntries(TABLES.map(t => [t, []]));

for (const line of src.split('\n')) {
  if (!KEEP_RE.test(line)) continue;
  const table = line.match(KEEP_RE)[1];
  let out = line.replace(/^INSERT INTO public\./, 'INSERT INTO ');
  // PG booleans → SQLite ints (dump uses bare true/false as values, never inside strings).
  out = out.replace(/, true(?=[,)])/g, ', 1').replace(/, false(?=[,)])/g, ', 0');
  byTable[table].push(out);
}

const orderedInserts = TABLES.flatMap(t => byTable[t]);
const counts = Object.fromEntries(TABLES.map(t => [t, byTable[t].length]));

const header = `-- Generated by scripts/convert-pg-dump.mjs from ${inPath}
-- Wipes app tables and re-imports rows with their original ids.
-- Child rows are deleted before parents; inserts are ordered parents-first.

DELETE FROM exercise_logs;
DELETE FROM goal_logs;
DELETE FROM goal_exercises;
DELETE FROM exercises;
DELETE FROM goals;
DELETE FROM sqlite_sequence WHERE name IN ('goals','exercises','goal_exercises','goal_logs','exercise_logs');

`;

writeFileSync(outPath, header + orderedInserts.join('\n') + '\n');

console.log(`Wrote ${orderedInserts.length} INSERTs to ${outPath}`);
for (const [t, n] of Object.entries(counts)) console.log(`  ${t}: ${n}`);
